config/routes.rb
SmileySamp::Application.routes.draw do
  resources :blogs

  root to: "blogs#index"

end

app/models/blog.rb
class Blog < ActiveRecord::Base
  attr_accessible :content, :title
  validates :title, presence: true, length: { :in => 3..50 }
  validates :content, presence: true, length: { :in => 5..10000 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  def new
  	@blog = Blog.new
  end

  def create
  	@blog = Blog.new(params[:blog])
  	if @blog.save
  	  redirect_to @blog
  	else
  	  render 'new'
  	end
  end

  def index
  	@blogs = Blog.all
  end

  def show
  	@blog = Blog.find(params[:id])
  end

  def edit
  	@blog = Blog.find(params[:id])
  end

  def update
  	@blog = Blog.find(params[:id])
  	if @blog.update_attributes(params[:blog])
  	  redirect_to @blog
  	else
  	  render 'edit'
  	end
  end

  def destroy
    @blog = Blog.find(params[:id])
    @blog.delete
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def emoji_renderer(content)
    emoji_object = Redcarpet::Markdown.new(MdEmoji::Render, :no_intra_emphasis => true)
    emoji_object.render(content).html_safe
  end
end

app/helpers/blogs_helper.rb
module BlogsHelper
  def generate_smiley(content)
    content = content.gsub(" :)", " #{image_tag '/assets/smile.png', alt: ':)'}")
    content = content.gsub(" ;)", " #{image_tag '/assets/naughty.png', alt: ';)'}")
    content = content.gsub(" :D", " #{image_tag '/assets/happy.png', alt: ':D'}")
    content = content.gsub(" :P", " #{image_tag '/assets/joke.png', alt: ':P'}")
    content = content.gsub(" :/", " #{image_tag '/assets/unhappy.png', alt: ':/'}")
    content = content.gsub(" :(", " #{image_tag '/assets/sad.png', alt: ':('}")
    content = content.gsub(" ;(", " #{image_tag '/assets/cry.png', alt: ';('}")

    content = content.gsub(" :-)", " #{image_tag '/assets/smile.png', alt: ':-)'}")
    content = content.gsub(" ;-)", " #{image_tag '/assets/naughty.png', alt: ';-)'}")
    content = content.gsub(" :-D", " #{image_tag '/assets/happy.png', alt: ':-D'}")
    content = content.gsub(" :-P", " #{image_tag '/assets/joke.png', alt: ':-P'}")
    content = content.gsub(" :-/", " #{image_tag '/assets/unhappy.png', alt: ':-/'}")
    content = content.gsub(" :-(", " #{image_tag '/assets/sad.png', alt: ':-('}")
    content = content.gsub(" ;-(", " #{image_tag '/assets/cry.png', alt: ';-('}")
    alt = ":'("
    content = content.gsub(" :'(", " #{image_tag '/assets/cry.png', alt: '" + alt + "'}")
  	content
  end
end

app/views/blogs/_blog_content.html.slim
b Title: 
= blog.title
br
b Content: 
/ = generate_smiley(blog.content).html_safe
/ br
= emoji_renderer(blog.content)

app/views/blogs/_error_messages.html.slim
- if object.errors.any?
  | The form contains 
  = pluralize(object.errors.count, "error")
  | .
  ul
    - object.errors.full_messages.each do |msg|
      li
        = msg

app/views/blogs/_fields.html.slim
= render 'error_messages', object: f.object
p
  = f.label :title
  br
  = f.text_field :title
br
p
  = f.label :content
  br
  = f.text_area :content
br

app/views/blogs/edit.html.slim
| Edit your blog...
br
br
= form_for(@blog)  do |f|
  = render 'fields', f: f
  = f.submit "Update"

app/views/blogs/index.html.slim
- if @blogs.count < 1
  | No blogs so far.. Create a new one
- else
  - @blogs.each do |blog|
    = render "blog_content", :blog => blog
    = link_to blog_path(blog) do
      font color="grey"
        b
          | Posted 
          = time_ago_in_words(blog.created_at)
          |  ago.
    br
br
br
= link_to "Post new blog", new_blog_path
br

app/views/blogs/new.html.slim
| Post new blog...
br
br
= form_for(@blog)  do |f|
  = render 'fields', f: f
  = f.submit "Post"

app/views/blogs/show.html.slim
| Blog details..
br
br
= render "blog_content", :blog => @blog
font color="grey"
  b
    | Posted 
    = time_ago_in_words(@blog.created_at)
    | ago.
/ br
/ = link_to "Edit", edit_blog_path(@blog)
/ |  | 
/ = link_to "Delete", @blog, method: :delete, data: { confirm: "Are you sure to delete?" }
hr
br
= link_to "Home Page", root_path

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SmileySamp</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/application.html.slim
html
  head
    title Smiley Sample Application
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
  body
    = yield